moov_im_user_connect:
    path:     /user/auth
    defaults: { _controller: MoovImUserBundle:User:connect }

moov_im_user_get_user_authenticated:
    path:     /user/me
    defaults: { _controller: MoovImUserBundle:User:getUserAuthenticated }