parameters:
    #Classes call
    moovim.jwt_token.class:     MoovIm\UserBundle\Services\JWTToken
    moovim.oauth_google.class:   MoovIm\UserBundle\Services\OAuthGoogle

    #Variables
    google_client_id: 1018703288165-svrbq2c31l94oh8luiontj9bg3j1jn06.apps.googleusercontent.com
    google_client_id_prod: 233892754495-lf20vqcl5fnlksp993gok44mqgnbg3e6.apps.googleusercontent.com
    google_client_secret: x1Zyd8kMiLwoxo-5WaUXZs1y
    google_client_secret_prod: PnCQR7tCcMp7WHRtdWGuketq
    oauth_access_token_url: https://accounts.google.com/o/oauth2/token
    oauth_people_api_url: https://www.googleapis.com/plus/v1/people/me/openIdConnect
    user_token_secret : tokengetcRm12

services:
    jwt_token:
        class: %moovim.jwt_token.class%
        arguments: [@service_container, %user_token_secret%]

    oauth_google:
        class: %moovim.oauth_google.class%
        arguments: [@request_stack, @doctrine.orm.entity_manager, @jwt_token, %oauth_access_token_url%, %oauth_people_api_url%, %google_client_id%, %google_client_secret%]
