moov_im_movies_coming_soon:
    path:     /movie/soon
    defaults: { _controller: MoovImMovieBundle:Movie:getMoviesComingSoon }

moov_im_movies_detail:
    path:     /movie/{id}
    defaults: { _controller: MoovImMovieBundle:Movie:detail }
